#! /usr/bin/sh

source ~/dotfiles/bash/git-completion.bash

if [ "$TERM" != "dumb" ] && [ -x /usr/local/bin/gdircolors ]; then
    eval "`gdircolors -b ~/dotfiles/bash/dir_colors`"
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

PATH=$HOME/bin:$PATH
PATH=/usr/local/bin:$PATH
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export EDITOR='vim'
export SFDCPATH=$HOME/Salesforce
